name: Load Poetry

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Check out code
        uses: actions/checkout@v2
      - name: Check current directory
        run: |
          pwd
          ls
      - name: Load Poetry dependencies
        run: |
          poetry install
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade wheel
          pip install argparse
          pip install functools
