name: Lint Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check of code
        uses: actions/checkout@v2

      - name: Execute semgrep
        uses: returntocorp/semgrep-action@v1

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check of code
        uses: actions/checkout@v2

      - name: execute cmd make code-quality
        run: make code-quality

  dockerfile-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check of code
        uses: actions/checkout@v2

      - name: Execute hadolint
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

  super-linter:
    needs: [pull-request]
    runs-on: ubuntu-latest
    steps:
      - name: Check of code
        uses: actions/checkout@v2

      - name: Run super-linter
        uses: github/super-linter@v4
        with:
          validations: all
