name: Lint Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.my_token }}

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check of code
        uses: actions/checkout@v2

      - name: Execute semgrep
        uses: returntocorp/semgrep-action@v1

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Install poetry
        run: |
          pip install poetry
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check of code
        uses: actions/checkout@v2
      - name: execute cmd make code-quality
        run: |
          poetry install
          poetry run black --check .

  dockerfile-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Check of code
        uses: actions/checkout@v2

      - name: Execute hadolint
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile

  super-linter:
    runs-on: ubuntu-latest
    needs: [pull_request, static-analysis, code-quality, dockerfile-analysis]
    steps:
      - name: Check of code
        uses: actions/checkout@v2

      - name: Execute super-linter
        uses: github/super-linter@v4
