name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9,3.10.6, 3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pip install poetry --upgrade pip

      - name: Install dependencies
        run: make install

      - name: Run tests and generate execution report
        run: make tests

      - name: Generate code coverage report
        run: make coverage-report

      - name: Save test execution report
        uses: actions/upload-artifact@v2
        with:
          name: test-execution-report
          path: report.html

      - name: Save code coverage report
        run: make coverage-report
