name: Test Workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test on Python 3.10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: make install

      - name: Run tests and generate execution report
        run: make tests

      - name: Generate code coverage report
        run: make coverage-report

      - name: Save test execution report
        uses: actions/upload-artifact@v2
        with:
          name: test-execution-report
          path: report.html

      - name: Save code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: htmlcov/
